### ISSUE TITLE
<XML> tag not output for sitemapindex.php and ror-rss.php

### ISSUE THREAD

**Issue by jamesleejiacheng** [RoumenDamianoff/laravel-sitemap#103]
Can you kindly change this line: `<?php '<'.'?'.'xml version="1.0" encoding="UTF-8"?>'."\n"; ?>` to: `<?= '<'.'?'.'xml version="1.0" encoding="UTF-8"?>'."\n"; ?>` please for `src/views/sitemapindex.php` and `src/views/ror-rss.php`? Thank you! 👍

**Comment by RoumenDamianoff** [comment]
Thank you for reporting this bug :+1:
