### ISSUE TITLE
Class sitemap does not exist

### ISSUE THREAD

**Issue by tobsbola** [RoumenDamianoff/laravel-sitemap#112]
$sitemap = App::make("sitemap");

This gives me this error on this line. Please I need a fix for laravel 5.1

**Comment by RoumenDamianoff** [comment]
Did you run ``composer dump-autoload -o`` after you add ``Roumen\Sitemap\SitemapServiceProvider::class`` to your providers in ``config/app.php`` ?

**Comment by tobsbola** [comment]
Yes i have tried it
Still didnt work

**Comment by tobsbola** [comment]
Thanks, it was actually a project wide issue, had to swich platform to another Laravel Installation and it worked seamlessly. @RoumenDamianoff thanks a bunch. Blessings!

**Comment by hktang** [comment]
I know it's an old issue, but it's weird that everything works on the vagrant box, but does not work in production. I have install dependencies and run `dump-autoload -o`, still trying to figure out what happened.
