### ISSUE TITLE
issue with large sitemap

### ISSUE THREAD

**Issue by AliTonbul** [RoumenDamianoff/laravel-sitemap#117]
I am trying to build a sitemap for over 4 million urls but it keeps bring back 500 error. is there a way to utilise the chunk method to overcome this problem. I used the sample but have had no luck. can you please help.

**Comment by RoumenDamianoff** [comment]
Hi, I was able to generate successfully example sitemap with 10 million urls without any problems.  

Can you share more information about your problem, what exactly is this error 500 you are getting, check your error logs, what  is your version of laravel, of this package, of php on the server, how much memory do you have, do you have swap partition, do you use ssd or some type of raid, is there something unusual about your setup? How exactly you are accessing this 4 million urls, do you read it from database, file or cache, do you clear your memory after reading a chunk of this records or you give it all directly to the generator?

**Comment by AliTonbul** [comment]
Thanks for the reply. It was a memory issue on my server.
