### ISSUE TITLE
Server Timeout error

### ISSUE THREAD

**Issue by deep88** [RoumenDamianoff/laravel-sitemap#124]
i want to create sitemap for a website that has more than 1 million pages.. i want to know how can i create that without effecting the server health. and without getting server timeout error..

**Comment by deep88** [comment]
.is it possible to run sitemap in time spans?

**Comment by RoumenDamianoff** [comment]
Yes, it is possible. You can see an example [here](https://github.com/RoumenDamianoff/laravel-sitemap/wiki/Generate-BIG-sitemaps).

**Comment by plehanov** [comment]
@deep88 This script should be carried out through the queue.
