### ISSUE TITLE
Google throw erro 500 when checking sitemap

### ISSUE THREAD

**Issue by seltix5** [RoumenDamianoff/laravel-sitemap#126]
i test it with google console and i always get error 500 with my sitemap.xml generated on the go :

https://www.publimaster.com/sitemap.xml

if i copy the content and create a real file i dont get error 500.

**Comment by itsavinash** [comment]
Try using it like this https://www.publimaster.com/sitemap.

**Comment by seltix5** [comment]
hi, thanks, i forgot to reply to this topic :/ the problem was not related with this plugin.
and btw, its great! :D

**Comment by seltix5** [comment]
hi, sorry to ask this itsavinash, but can you please remove the link please, or delete this issue since it wasnt a issue with the plugin? thanks.
