### ISSUE TITLE
Add option to set hostname

### ISSUE THREAD

**Issue by ryanrca** [RoumenDamianoff/laravel-sitemap#127]
Hi,

When I run your code from a button in our admin section, the generated sitemaps are prefect!

I made an Atrisan command that runs the same code, but the generated sitemaps produce the loc to localhost, like this:

```
<url>
    <loc>https://localhost/royalty-free-music/track/liadovmemory-alexander-pushkin-op49/TRA-CEL04</loc>
        <priority>0.85</priority>
        <lastmod>2017-01-10T00:29:46+00:00</lastmod>
        <changefreq>monthly</changefreq>
  </url>
  <url>
    <loc>https://localhost/royalty-free-music/track/albinoniconcerto-op9-n11allegro/TRA-CEL06</loc>
        <priority>0.85</priority>
        <lastmod>2017-01-10T00:29:46+00:00</lastmod>
        <changefreq>monthly</changefreq>
  </url>
... etc.
```
I need them to have the correct hostname like is generated when running in a controller from a route:
```
 <url>
    <loc>https://stockmusic.net/royalty-free-music/track/liadovmemory-alexander-pushkin-op49/TRA-CEL04</loc>
        <priority>0.85</priority>
        <lastmod>2017-01-10T00:30:55+00:00</lastmod>
        <changefreq>monthly</changefreq>
  </url>
  <url>
    <loc>https://stockmusic.net/royalty-free-music/track/albinoniconcerto-op9-n11allegro/TRA-CEL06</loc>
        <priority>0.85</priority>
        <lastmod>2017-01-10T00:30:55+00:00</lastmod>
        <changefreq>monthly</changefreq>
  </url>
```

How can I set the host name so I can generate the sitemaps from an artisan command?  I need this so I can automate the sitemap generation.

Thanks!

**Comment by ryanrca** [comment]
I figured it out through code inspection.

in config/app.php the url field controls this.
I set url and my sitemaps are updating properly.

This would be a good thing to document someplace.

**Comment by Jonybang** [comment]
But dynamic change app.url from code wont work :(
For example: 
```
\Config::set('app.url', 'http://' . $domain);
echo(config('app.url')); // displaying domain, which was set
// but then sitemap rendered with previous app.url, which was before set
```

**Comment by Jonybang** [comment]
Maybe because $channel variable with url from config dont used in xml template:
https://github.com/RoumenDamianoff/laravel-sitemap/blob/master/src/Roumen/Sitemap/Sitemap.php#L356
