### ISSUE TITLE
Setting cache but always creating new sitemap

### ISSUE THREAD

**Issue by katiany** [RoumenDamianoff/laravel-sitemap#138]
Hi, there.

I'm trying to use this repository example to create cached sitemap. Even though I use this code:
```
$sitemap->setCache('laravel.sitemap', 60);
if (!$sitemap->isCached())
{
     // never enters here
}
```
I checked that it's never creating my sitemap properly.

Anyone using cache know what must be the issue here?

Thanks in advance.

**Comment by katiany** [comment]
I was trying to use `store` with cache. I was reading the code and `store` forces cache to be `false`.

**Comment by fikoborquez** [comment]
I think that should be explained in [Example: How to generate sitemap file](https://github.com/RoumenDamianoff/laravel-sitemap/wiki/Generate-sitemap)
