### ISSUE TITLE
How Create Tree View SiteMap?

### ISSUE THREAD

**Issue by farshidrezaei** [RoumenDamianoff/laravel-sitemap#140]
i want create site map like that : 

```
O-Home
|__o-About
|__o-Contact
|__o-Articles
|    |__o-First Article
|    |__o-Second Article
|
|__o-Pages
|    |__o-First Page
|    |__o-Second Page
|
|__o-Media
|    |__o-Music
|    |__o-Iamge
|         |__o-Jpeg
|         |__o-Png
|...
....

```
Can i do it with this package?

**Comment by farshidrezaei** [comment]
why close???? 😠

**Comment by RoumenDamianoff** [comment]
Hi, because your issue is not a report of bug or a problem related to this package. You are asking a question (it's not very clear) about type of sitemap not in the context of this package. You can't create what you want with it, it's not designed for this job, sorry.
