### ISSUE TITLE
Sitemap Limits

### ISSUE THREAD

**Issue by graystevens** [RoumenDamianoff/laravel-sitemap#27]
How well does this work with the known sitemap limits, such as 50,000 URLs or 10mb (see [here](http://www.sitemaps.org/faq.html#faq_sitemap_size) for details).

Can this automatically identify indexes over the 50,000 limit and produce multiple indexes when this occurs?

**Comment by ChristianPV** [comment]
@RoumenDamianoff i think you should open this issue as this is currently not implemented... I came into this issue before and now again. My previous implemention was done on application logic. I haven't modified a line of code on this library. They way i did it before was by doing an index with multiple sitemaps each one being a model but the limitation a have run to now is that one model has currently over 50,000 records so i have to divide again. Do you think this is the right way to do it? can we somehow implement this on the library for anyone else coming into this issue?
