### ISSUE TITLE
Sitemap Video Extension

### ISSUE THREAD

**Issue by benbowler** [RoumenDamianoff/laravel-sitemap#29]
Do you support the Google Video extension for the sitemap protocol? If not I'll build and submit a pull request!

https://support.google.com/webmasters/answer/80472?hl=en

**Comment by hemratna** [comment]
@benbowler  @RoumenDamianoff 
Hi, 
I want to add www to my urls in sitemap.
So what is the preferable way to do this?

**Comment by fikoborquez** [comment]
is there any news about this issue?
I'd like to know if it was implemented this option

Greetngs!

**Comment by benbowler** [comment]
I still haven't built it out for our needs but will let you know if I do.
Likewise if you build it in please contribute back.


--
*Ben Bowler*

ben@benbowler.com | +44 7983 883 035

**Comment by fikoborquez** [comment]
Ok, thanks for answer :). I'll try to do it.

**Comment by RoumenDamianoff** [comment]
I just added very raw support for this in dev-master, the 8th param of add() is now array of arrays for videos (you can have multiple videos on single page). Some tags must be arrays (eg. uploader, price, gallery_loc etc), more info https://developers.google.com/webmasters/videosearch/sitemaps. 

Example usage:

```php
        $sitemap->add(
            'http://www.example.com/videos/some_video_landing_page.html',
            '2015-06-18T17:00:00+02:00',
            '1.0',
            'weekly',
            [],
            null,
            [],
            [[
                'thumbnail_loc' => 'http://www.example.com/thumbs/123.jpg',
                'title' => 'Grilling steaks for summer',
                'description' => 'Alkis shows you how to get perfectly done steaks every time',
                'content_loc' => 'http://www.example.com/video123.flv',
                'uploader' => [
                                       'uploader' => 'Someone',
                                       'info' => 'blabla'
                                       ]
            ]]
            );
```

**Comment by fikoborquez** [comment]
wow, thanks. Can I use it with L4 version?

**Comment by fikoborquez** [comment]
Thanks for add this to L4 branch :D
