### ISSUE TITLE
XML declaration allowed only at the start of the document

### ISSUE THREAD

**Issue by luharanu** [RoumenDamianoff/laravel-sitemap#31]
Hi !
I have the following error when I render the sitemap, need help please.
![capture](https://cloud.githubusercontent.com/assets/5591232/4925141/d73649d0-6528-11e4-8c1e-513b82535c24.PNG)

**Comment by jelled** [comment]
I know the OP was using Laravel 4.2, however I was getting a similar output error in Laravel 4.3 due to a blade change. For anyone using 4.3 the fix is to change line 1 of vendor/roumen/sitemap/src/views/xml.blade.php to

    {!! '<'.'?'.'xml version="1.0" encoding="UTF-8"?>' !!}

**Comment by luharanu** [comment]
with this {{ '<'.'?'.'xml version="1.0" encoding="UTF-8"?>' }}, the problem has been solved. Really thank you.
