### ISSUE TITLE
IOC Container seperation

### ISSUE THREAD

**Issue by Bulmer** [RoumenDamianoff/laravel-sitemap#4]
I tried to run three separate instances of Sitemap in the same Controller method (to create 4 different sitemap xml files, using store()) but found that they had very strange behaviour. 
To better explain, I tried to 
$category_sitemap = App::make ( "sitemap" );
$category_sitemap->add(.............
$category_sitemap->store( 'xml', 'sitemapcategories' );
$product_sitemap = App::make ( "sitemap" );
$product_sitemap->add(.............
$product_sitemap->store( 'xml', 'sitemapproducts' );
....but the result of sitemapproducts.xml also contains the items in sitemapcategories.xml.
Is there a way to create separate Sitemap instances within the same controller method?
Cheers.

**Comment by ultrono** [comment]
Appreciate this is an old issue and only semi- related. I generating multiple sitemaps with some kind of loop you still to resolve a fresh instance of the class from the container.

Maybe some kind of reset method we can call to clear internal class variables would be good?
