### ISSUE TITLE
Google Webmaster Tools returns error

### ISSUE THREAD

**Issue by dylanglockler** [RoumenDamianoff/laravel-sitemap#44]
I generated a basic sitemap (www.lovelaundry.com/sitemap) and submitted for test to Google Webmaster Tools and it came back with the following errors:

Invalid URL  This is not a valid URL. Please correct it and resubmit.  Errors: 3

URL: HTTP/1.0 200 OK
URL: Cache-Control: no-cache
URL: Content-Type: text/xml; charset=utf-8

They don't seem to like those first three lines.

**Comment by RoumenDamianoff** [comment]
This lines shouldn't be there, there is problem somewhere else, other package, filter, server config etc.
