### ISSUE TITLE
Translation management is buggy

### ISSUE THREAD

**Issue by potsky** [RoumenDamianoff/laravel-sitemap#45]
Hi !

If I do not provide any translation in Sitemap, I have this buggy XML (both xhtml are wrong) :

```
  <url>
    <loc>https://www.nr.dev</loc>
		<xhtml:link rel="alternate" hreflang="h" href="h" />
		<xhtml:link rel="alternate" hreflang="h" href="h" />
		<priority>1.0</priority>
		<lastmod>2014-06-09T20:10:00+02:00</lastmod>
		<changefreq>daily</changefreq>
  </url>
```

If I set a translation array like this : 

```
array(
    array(
        'url'      => URL::to( LaravelLocalization::getLocalizedURL( 'en' , $path ) ),
        'language' => 'en'
    ),
    array(
        'url'      => URL::to( LaravelLocalization::getLocalizedURL( 'fr' , $path ) ),
        'language' => 'fr'
    )
)
```

it is buggy too because I have a `htmlentities() expects parameter 1 to be string, array given` on line 100 in `vendor/roumen/sitemap/src/Roumen/Sitemap/Sitemap.php`

Then I remove the xmlentities :

```
/*
            if ($translation)
            {
                foreach ($translation as $key => $value)
                {
                    $translation[$key] = htmlentities($value, ENT_XML1);
                }
            }
*/
```

But the XML template is wrong too. When I `dd($item)` in the xml template, I get these lines :

```
array (size=7)
  'loc' => string 'https://www.nr.dev' (length=18)
  'lastmod' => string '2014-06-09T20:10:00+02:00' (length=25)
  'priority' => string '1.0' (length=3)
  'freq' => string 'daily' (length=5)
  'images' => null
  'title' => null
  'translation' => 
    array (size=2)
      'en' => string 'https://www.nr.dev/en' (length=21)
      'fr' => string 'https://www.nr.dev/fr' (length=21)
```

So you should not parse translations like this :

```
if (!empty($item['translation'])) {
  foreach ($item['translation'] as $translation) {
    echo "\t\t" . '<xhtml:link rel="alternate" hreflang="' . @$translation['language'] . '" href="' . @$translation['url'] . '" />' . "\n";
  }
}
```

But like this :

```
if (!empty(@$item['translation'])) {
  foreach ($item['translation'] as $lang => $url ) {
    echo "\t\t" . '<xhtml:link rel="alternate" hreflang="' . $lang . '" href="' . $url . '" />' . "\n";
  }
}
```

Right ? Do I need to modify some other things ? Do you want a pull request ?

**Comment by mabasic** [comment]
It seems that someone messed up somewhere. I am searching history to find the cause.

**Comment by mabasic** [comment]
This is the problem:

```
if ($translation)
            {
                foreach ($translation as $key => $value)
                {
                    $translation[$key] = htmlentities($value, ENT_XML1);
                }
            }
```

This is the solution:

```
if ($translations)
            {
                foreach($translations as $translation)
                {
                    foreach ($translation as $key => $value)
                    {
                        $translation[$key] = htmlentities($value, ENT_XML1);
                    }
                }
            }
```

And you have to change parameter `translation` to `translations` in method declaration and at the end of the method.

I will post a PR later this afternoon.

**Comment by Anahkiasen** [comment]
Can we get this bugfix backported to the L4 branch? Currently the L4 version is broken because of this

**Comment by potsky** [comment]
+1

**Comment by jonasva** [comment]
+1

**Comment by jonasva** [comment]
I forked and added a laravel4 branch: https://github.com/jonasva/laravel-sitemap/tree/laravel4. 
@RoumenDamianoff Could you add a laravel4 branch as well for us to merge fixes into?

**Comment by RoumenDamianoff** [comment]
Try v2.4.16 for laravel 4, it should work fine, this bug was fixed long time ago, but the fix was not included properly in laravel4 latest tag.

I created laravel4 branch for future PRs regarding version 4 of laravel. If you want to contribute make pr to this branch, not master.

**Comment by jonasva** [comment]
Thx

**Comment by potsky** [comment]
Thanx
