### ISSUE TITLE
Cannot add simple route

### ISSUE THREAD

**Issue by patrickml** [RoumenDamianoff/laravel-sitemap#49]
I am getting this error no matter what I do to the add function.

strtotime() expects parameter 1 to be string, object given (View: /home/vagrant/Code/****/www/vendor/roumen/sitemap/src/views/xml.blade.php)

This is where the error is being thrown from
 if ($item['lastmod'] !== null) {
  echo "\t\t" . '<lastmod>' . date('Y-m-d\TH:i:sP', strtotime($item['lastmod'])) . '</lastmod>' . "\n";
}
 
This is what i tried to add 
$sitemap->add(URL::to('/'), '2012-08-25T20:10:00+02:00', '1.0', 'daily');

**Comment by ClausMunch** [comment]
Your 'lastmod' is most likely of the timestamp datatype.

**Comment by mabasic** [comment]
@patrickml Hate to do this, but see here https://github.com/laravelista/Bard
