### ISSUE TITLE
Fatal Error in Dev Version

### ISSUE THREAD

**Issue by mandersondesign** [RoumenDamianoff/laravel-sitemap#51]
Just so you know, the dev version is throwing a fatal error:

```
PHP Fatal error:  
Call to undefined method Roumen\Sitemap\SitemapServiceProvider::loadViewsFrom() 
in /root-dir/vendor/roumen/sitemap/src/Roumen/Sitemap/SitemapServiceProvider.php on line 21

{
 "error": { 
  "type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException",
  "message":"Call to undefined method Roumen\\Sitemap\\SitemapServiceProvider::loadViewsFrom()",
  "file":"\/root-dir\/vendor\/roumen\/sitemap\/src\/Roumen\/Sitemap\/SitemapServiceProvider.php",
  "line":21
  }
}
```

**Comment by benharold** [comment]
+1 Please fork the project for L5 support.

**Comment by RoumenDamianoff** [comment]
Next version will support laravel 5 and all this issues hopefully will be resolved. I can't give an exact ETA for this, but I hope it will be done soon, maybe before the end of this weekend.

Currently master is unstable and laravel 5 support is not tested.

**Comment by mvalster** [comment]
`"roumen/sitemap": "2.4.15"` also works!

**Comment by 0x1AD2** [comment]
@mvalster thanks for that tip!
