### ISSUE TITLE
Error parsing attribute name - laravel 4.2

### ISSUE THREAD

**Issue by tylerjvick** [RoumenDamianoff/laravel-sitemap#54]
Hey there,

I like this project a lot, and had intended to integrate it into my new site. Though the sitemap generates fine in my development environment, I'm getting the following error after deploying it to my server:

    This page contains the following errors:
    
    error on line 1 at column 49: error parsing attribute name
    Below is a rendering of the page up to the first error.

I cannot figure out what is wrong, and the error I'm getting isn't incredibly specific... Here's the code I'm using to generate the sitemap, again which is working fine via php artisan serve:

	// Create new sitemap
	$sitemap = App::make("sitemap");

	// set cache if needed
	// $sitemap->setCache('laravel.sitemap', 3600);

	// Add item to sitemap

	$sitemap->add(URL::to('/'), date('c', time()), '1.0', 'daily');
	$sitemap->add(URL::to('/about'), date('c', time()), '1.0', 'weekly');
	$sitemap->add(URL::to('/projects'), date('c', time()), '1.0', 'weekly');
	$sitemap->add(URL::to('/stuff'), date('c', time()), '1.0', 'weekly');

	// display sitemap default as xml
	return $sitemap->render('xml');

Any help with this issue would be greatly appreciated, thanks!

**Comment by jimmygle** [comment]
The issue is here:

```
<?xml version="1.0" encoding="UTF-8"?><urlsetxmlns="http://www.sitemaps.org/schemas/sitemap/0.9"xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"xmlns:xhtml="http://www.w3.org/1999/xhtml"xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
```

It's in the ```<urlsetxmlns="...``` which needs to be ```<urlset xmlns="...``` with the added space.
