### ISSUE TITLE
Undefined function loadViewsFrom() 

### ISSUE THREAD

**Issue by yespbs** [RoumenDamianoff/laravel-sitemap#61]
Roumen\Sitemap\SitemapServiceProvider makes call to $this->loadViewsFrom() which exists in Illuminate\Support\ServiceProvider for Laravel 5 ONLY, 

Lavravel 4 does not have this method, 

Using Laravel 4.2 and "roumen/sitemap": "~2.4",

As per readme, it should not conflict.

**Comment by RoumenDamianoff** [comment]
Hi, are you sure you're using the right version? Because I can't reproduce this error with Laravel 4.2 and version 2.4.15 of the package.

**Comment by yespbs** [comment]
yes, if you try to run php artisan optimize or composer dump-auto the error shows.

"laravel/framework": "4.2.*",
"roumen/sitemap": "~2.4",

**Comment by yespbs** [comment]
My composer.lock showing
 "name": "roumen/sitemap",
  "version": "v2.5.2",

may be its cached, let me retry

**Comment by yespbs** [comment]
same after removing lock

**Comment by yespbs** [comment]
Hi,

Thanks, I found and fixed the issue, fixed last stable version for sitemap to 2.4.15 which fixed the issue
