### ISSUE TITLE
ReflectionException (-1)  Class sitemap does not exist 

### ISSUE THREAD

**Issue by rslanzi** [RoumenDamianoff/laravel-sitemap#64]
I've just installed sitemap 2.4.15 in Laravel 4.2 but when I call the sitemap route I get the error "Class sitemap does not exist" on the line with $sitemap = App::make("sitemap");.

I've followed the basic example finded here -> https://github.com/RoumenDamianoff/laravel-sitemap/wiki/Generate-sitemap

Can you help me?

**Comment by tobsbola** [comment]
Please am experiencing this same issue on laravel 5.1
