### ISSUE TITLE
Cache reset

### ISSUE THREAD

**Issue by alexey-fut** [RoumenDamianoff/laravel-sitemap#65]
How to update/reset the cache without something like

if ($ request->get ('nocache')) {
    $sitemap->setCache ('sitemap', 0);
}
And now we have unnecessary calls to the database. For example post images..

I think the first version was better..

$sitemap = App::make("sitemap");

// but isCached nothing to know about key :-)

    if ($sitemap->isCached() && $request->get ('nocache')) {
        return $sitemap->render('xml');
    }

....

$sitemap->setCache('sitemap', 3600);

**Comment by RoumenDamianoff** [comment]
You don't need to call the database if there is unexpired cache, you call it only if there is no cache. See the [example in the wiki](https://github.com/RoumenDamianoff/laravel-sitemap/wiki/Dynamic-sitemap) isCached() "knows" what is the key and uses it to check for unexpired cache. 

Why use ``$request->get('nocache'))`` ?

**Comment by alexey-fut** [comment]
Thank you, i didn't missunderstood, it was deep night..
I was misled [example in the wiki](https://github.com/RoumenDamianoff/laravel-sitemap/wiki/Sitemap-index)

nocache - Something like a quick easy way to update cache data for example: was added images to posts...
