### ISSUE TITLE
rel alternate

### ISSUE THREAD

**Issue by matiux** [RoumenDamianoff/laravel-sitemap#66]
Is there a way to include a rel="alternate" for the language pages and mobile?
```
  <url>
    <loc>http://www.example.com/english/</loc>
    <xhtml:link 
                 rel="alternate"
                 hreflang="de"
                 href="http://www.example.com/deutsch/"
                 />
    <xhtml:link 
                 rel="alternate"
                 hreflang="de-ch"
                 href="http://www.example.com/schweiz-deutsch/"
                 />
    <xhtml:link 
                 rel="alternate"
                 hreflang="en"
                 href="http://www.example.com/english/"
                 />
<xhtml:link
    rel="alternate"
    media="only screen and (max-width: 640px)"
    href="http://m.example.com/page-1" />
  </url>
```

**Comment by matiux** [comment]
Ok,
I have seen that xml.blade.php already provides the if statement to insert rel="alternate" for the languages. So I was able to insert my url.

Instead, for mobile rel alternate I thought about doing a pull request to implement the feature.

What do you tink?

**Comment by RoumenDamianoff** [comment]
There are other ways to do this, for example add custom view for mobile sitemaps and use sitemapindex or some other logic like canonical link tags to deal with duplicates. But still its not a bad idea this attribute to be optional (not only for mobile pages). I may do this in the next update.

**Comment by matiux** [comment]
According to google specs,the right way to handle mobile url, is of indicate rel="alternate" attribute into desktop sitemap

https://developers.google.com/webmasters/mobile-sites/mobile-seo/configurations/separate-urls?hl=en

**Comment by RoumenDamianoff** [comment]
Hi, this should work now, see example [here](https://github.com/RoumenDamianoff/laravel-sitemap/wiki/Dynamic-sitemap) (add item with translations).
