### ISSUE TITLE
Call to undefined method Roumen\Sitemap\SitemapServiceProvider::loadViewsFrom()

### ISSUE THREAD

**Issue by esedArk** [RoumenDamianoff/laravel-sitemap#69]
I'm Using

    "laravel/framework": "4.2.*",
    "roumen/sitemap": "~2.5"

**Comment by RoumenDamianoff** [comment]
Hi, you are using wrong version for laravel 4 you must use sitemap version 2.4.*

**Comment by esedArk** [comment]
Okay I solved!
Change API 
"roumen/sitemap": "~2.4" to "roumen/sitemap": "2.4.*"

Tnks!
