### ISSUE TITLE
caching documentation

### ISSUE THREAD

**Issue by dwenaus** [RoumenDamianoff/laravel-sitemap#75]
On this page (https://github.com/RoumenDamianoff/laravel-sitemap/wiki/Dynamic-sitemap) you say that caching is in minutes, but the default in the code is 3600 which, makes me think it's actually seconds. I could not find out if it's seconds or minutes...

**Comment by fikoborquez** [comment]
I think it is in minutes, because is using laravel cache.
Notice that the int represent minutes.

http://laravel.com/docs/5.0/cache#cache-usage
https://github.com/RoumenDamianoff/laravel-sitemap/blob/master/src/Roumen/Sitemap/Sitemap.php#L176
