### ISSUE TITLE
XML Parsing Error: XML or text declaration not at start of entity

### ISSUE THREAD

**Issue by danboh** [RoumenDamianoff/laravel-sitemap#77]
Configured for Laravel 4.2 using 2.4.*, but when using the basic example:

class SitemapController extends BaseController{
    public function index(){
        // create sitemap
        $sitemap_posts = App::make("sitemap");
        // set cache
        $sitemap_posts->setCache('laravel.sitemap-posts', 3600);
        // add items
        $posts = DB::table('posts')->orderBy('created_at', 'desc')->get();
        foreach ($posts as $post){
            $sitemap_posts->add($post->slug, $post->updated_at, "", "");
        }
        // show sitemap
        return $sitemap_posts->render('xml');
    }
}

I get the error:
XML Parsing Error: XML or text declaration not at start of entity
Location: http://dev.mydomain.com/sitemap
Line Number 2, Column 1:
<?xml version="1.0" encoding="UTF-8"?>
^

It seems that there's an extra line being added to the xml template

**Comment by fikoborquez** [comment]
I use ob_end_clean() function in my controller, before render the view.
I don't know if there is a problem with module or my views, but using the function it works.

**Comment by almamundinajpuri** [comment]
@fikoborquez ,
Thanks for the tips. Worked for me too.
```
ob_end_clean();
return $sitemap->render('xml');
```
