### ISSUE TITLE
Strange caching problem

### ISSUE THREAD

**Issue by C0d3Craft3r** [RoumenDamianoff/laravel-sitemap#83]
I have very strange problem with caching of sitemaps, when I render sitemap it shows different version of the view and updates only parts of it but not everything.. new links are displayed, but without correct namespaces and validation fails, xml in the view is cached and not updated, but only the php part.. I have no idea what's going on.

Same code works on my mac with php 5.6, but not on ubuntu with the same version of php, in both cases I use redis. This happens on new fresh install of laravel 5.2 and on laravel 5.1.

**Comment by RoumenDamianoff** [comment]
Do you have any sitemap views publish to your resources/views/vendor/sitemap directory? Maybe you use ``artisan vendor:publish`` after install, but not after latest updates and now you have older views with different structure. On fresh install of 5.2 this may happen if you copy your older views to it?

**Comment by C0d3Craft3r** [comment]
:+1:  yes this was the problem, thank you!

 I just deleted views/vendor folder and now everything is fine.
