### ISSUE TITLE
Is it possible to have a custom stylesheet?

### ISSUE THREAD

**Issue by danbovey** [RoumenDamianoff/laravel-sitemap#85]
Adding a default style from /vendor is a great addition, but is it configurable?

Something like `custom_style` below `use_styles` in the config to include a custom .xsl file

EDIT: Only just seen that the new changes put the xsl in **public/**vendor.. gg me

**Comment by RoumenDamianoff** [comment]
You can use custom styles, but any changes in ``public/vendor`` directory will be overwritten. To use your custom styles you need to set location with ``$sitemap->model->setSloc('/xsl/')`` where ``/xsl/`` is located in your public folder or url like ``http://mydomain.com/xsl/`` (with ``/`` in the end). You should place there your styles with same names like the original ones. 

This is still work in progress and soon will be improved and documented with examples.
