### ISSUE TITLE
Can't configure file store path with $sitemap->store() 

### ISSUE THREAD

**Issue by Charkhan** [RoumenDamianoff/laravel-sitemap#86]
Hey,

Just ran into this problem : I want to generate sitemaps with big data that I will put via SFTP on another repo.

To do so, I need to put the sitemaps on a specific folder to let another task upload files to the public website.

I wish to be able to do so :
```php

$sitemap->store($format, $filename, $pathToStore)
```

I can do a PR if you like the idea, I think there is not much to change.

**Comment by RoumenDamianoff** [comment]
Hi, please see if this works for you.

**Comment by Charkhan** [comment]
That is exactly what I had in mind, thanks !

I'll test it by tommorow, I'll let you know.

**Comment by Charkhan** [comment]
Ok, It works.

Just one more question : Do you have any function to define a custom bumber of urls / sitemap ?

Ex: I want to generate a sitemapindex with 10000 urls / sitemap opposed to the 50000 that is by default.

Is that possible ?

**Comment by Charkhan** [comment]
Pointed out some pitfall on your last commit ! :)

**Comment by RoumenDamianoff** [comment]
Ok, I'll see what I can do in the weekend.

**Comment by Charkhan** [comment]
Thanks, If you need any help, just let me know ! You're awesome !

**Comment by Charkhan** [comment]
Up ? :)

**Comment by F1NaL** [comment]
Can U up version ?

**Comment by RoumenDamianoff** [comment]
Hi, you could update to `v2.6.2` (released today).
