### ISSUE TITLE
Nested sitemapindex

### ISSUE THREAD

**Issue by Murwa** [RoumenDamianoff/laravel-sitemap#87]
Hey @RoumenDamianoff thanks for this amazing stuff. How can I create a sitemapindex of sitemapindexes?

**Comment by RoumenDamianoff** [comment]
Hi, I don't think this is possible, sitemap index could only contain sitemaps (max 50,000), not other sitemap indexes. But you could create many sitemap indexes and submit them separately to google (via webmasters tools) or reference all of them in ``robots.txt`` so crawlers could see them.

**Comment by Murwa** [comment]
Cool
