### ISSUE TITLE
error on line 2 at column 6: XML declaration allowed only at the start of the document

### ISSUE THREAD

**Issue by kkyeboah** [RoumenDamianoff/laravel-sitemap#89]
This error appears for the Laravel 4 package. First line of xm.blade.php is `{{ '<'.'?'.'xml version="1.0" encoding="UTF-8"?>' }}`. This gives the error message `error on line 2 at column 6: XML declaration allowed only at the start of the document`. Changing it from that to `<?php '<?xml version="1.0" encoding="UTF-8"?>' ?>` works. As this is a package is there anyway to point to a custom blade file or better still, this should be fixed.

Has anyone else faced this issue?

**Comment by RoumenDamianoff** [comment]
Hi, what version are you using to get this error?

You can use custom views or change the default ones in your ``app/views/vendor/sitemap``. You need to publish this package views ``php artisan views:publish roumen/sitemap`` or to create this folder manually and place there your sitemap views.
