### ISSUE TITLE
Branch for Laravel 4

### ISSUE THREAD

**Issue by sivaganeshsg** [RoumenDamianoff/laravel-sitemap#92]
Hi, 

Is there working branch for L 4.2 ?

**Comment by RoumenDamianoff** [comment]
``dev-laravel4`` ([here](https://github.com/RoumenDamianoff/laravel-sitemap/tree/laravel4)) is the branch for laravel 4.x.

 I can't promise regular updates, but I'll try to keep it on pair with the latest releases.

**Comment by sivaganeshsg** [comment]
Is there any stable branch for v4.2 instead of dev branch ?

Also, it would be great if you could mention it in Readme file for other users.
