### ISSUE TITLE
Public path not in base_path

### ISSUE THREAD

**Issue by fonz-lu** [RoumenDamianoff/laravel-sitemap#94]
Hi, 

I had an issue with the public directory. My public directory is not in the base directory. The structure is like this

*public
*laravel

There was a problem when I tried to store a sitemap. In the SitemapServiceProvider.php I had to change this
```php
$this->publishes([
            __DIR__ . '/../../public' => base_path('/vendor/sitemap')
        ], 'public');
    }
```

to this

```php
$this->publishes([
            __DIR__ . '/../../public' => public_path('/vendor/sitemap')
        ], 'public');
    }
```

Is there any other way to change the public directory without tampering with your script?

Thanks

**Comment by RoumenDamianoff** [comment]
Hi, this is fixed in the master branch and will be included in next version.
