### ISSUE TITLE
 Fatal error: Uncaught Error: Class 'Route' not found in

### ISSUE THREAD

**Issue by hosamalzagh** [RoumenDamianoff/laravel-sitemap#95]
how can i fix it 

fist used

**Comment by RoumenDamianoff** [comment]
Hi, please give more information about this error, full dump, example code etc.

**Comment by hosamalzagh** [comment]
sir is this laravel-sitemap work stand alone with my code or it need part from  laravel fram work

**Comment by RoumenDamianoff** [comment]
You'll need to include it as composer package to laravel framework app, it doesn't work stand alone.
