### ISSUE TITLE
sitemap xml option not rendering

### ISSUE THREAD

**Issue by VerzatileTom** [RoumenDamianoff/laravel-sitemap#96]
`return $sitemap->render('xml');` is not renderring xml but when you check the page source it is not empty.

Other rendering option works though. Any idea why this happen and how to fix this?

**Comment by RoumenDamianoff** [comment]
Give me an example of this.

**Comment by VerzatileTom** [comment]
Disregard this problem, it seems only not working on my local but working on our live server. Thanks for this amazing library by the way!
