### ISSUE TITLE
sitemapindex with path

### ISSUE THREAD

**Issue by aryeharmon** [RoumenDamianoff/laravel-sitemap#99]
There is no way to generate the sitemapindex with a path?

all links are relative to the base url

**Comment by RoumenDamianoff** [comment]
Please, give me an example of what you are doing.

**Comment by alanhr** [comment]
Hi @RoumenDamianoff ,Can you tell me how to change the sitemap folder ?
I changed the name of the folder public to public_html and after changed the sitmap not work anymore

**Comment by nitinsurana** [comment]
+1
